coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshhold: 5%
        target: 90%
    patch:
      default:
        threshhold: 5%
        target: 70%


